spring:
  application:
    name: base
  datasource:
    url: jdbc:mysql://localhost:3306/product?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    server:
      enable-self-preservation: false
